name: Issues Listener
on: issues
jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: Listen to Issues
        env:
            GITHUB_EVENT_NAME: ${{ github.event_name }}
            GITHUB_EVENT_ACTION: ${{ github.event.action }}
            GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
            GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
            echo "Listening to issues events..."
            echo "Event Name: $GITHUB_EVENT_NAME "
            echo "Action: $GITHUB_EVENT_ACTION"
            echo "Issue Title: $GITHUB_ISSUE_TITLE"
            echo "Issue Body: $GITHUB_ISSUE_BODY"